// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dapxjgvvvxkbmshwnsvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcHhqZ3Z2dnhrYm1zaHduc3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDU2NTgsImV4cCI6MjA3MTk4MTY1OH0.BJugBd6fSxy_VRKHGCwj7iIpeWhhJ7W28dapyTwVJmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});